### ISSUE TITLE
Connection Issues for some people

### ISSUE THREAD

**Issue by bradxy** [vRP-framework/vRP#468]
Sometimes people are unable to join, and are stuck on the connection screen, stuck at Checking Whilelisted.. 

They show up in the admin menu under users even when not connected

Seems tho vrp loads them and if they disconnect vrp is not removing them as a loaded player or something, a server restart is the only fix so far...

**Comment by ImagicTheCat** [comment]
You mean they are in the player list ? If that's the case, you should read something else like "Loading user...", so something is wrong, not directly from the vRP login code.

**Comment by bradxy** [comment]
They are not registered by vRP, just non existent until a server restart, and it happens at random, and sudden... It has happened to me with a fresh server restart, not even joining once... It will effect one person and while everyone else can connect with no issues...

**Comment by ImagicTheCat** [comment]
Probably not related to vRP.

**Comment by bradxy** [comment]
Was indeed a issue with the load screen I was using, thanks!

**Comment by bradxy** [comment]
After further testing this issue, It is still happening with out the loading screen... 
I am able to reproduce the issue on a fresh install of vrp2 on a local windows server.

1. Connect to server
2. In F8 disconnect
3. Connect to server without quitting - will not connect
4. Quit fivem
5. Now locked out from server stuck on "Check Whitelisted"

It seems when typing disconnect in F8 while joining, and then re-joining without quitting fivem breaks the server... Not sure if this is a fivem thing or what...

**Comment by ImagicTheCat** [comment]
Try to reproduce without vRP and a resource using the deferred FiveM API.

**Comment by bradxy** [comment]
This issue only happens with steam open...

I tried to reproduce with vrp disabled and it stopped happening...

**Comment by bradxy** [comment]
adding self:dropPlayer(source) 
to the top of 
function vRP:onPlayerConnecting(source, name, setMessage, deferrals) 

Forces a user to disconnect if "somehow" still registered to vrp2 when connecting

Probably not the right way to do it but it seems to have fixed the issue

**Comment by yuricampolongo** [comment]
I'm still having this problem and I've made the change to add the line self:dropPlayer(source).

Is there any other ideas?

**Comment by zxMatri-x** [comment]
Where should I put this?

**Comment by IllInuz** [comment]
Having the same issue, and even with the above fix, if they reconnect right after they disconnected peoples menus will get stuck and unable to use, unless a server restart is done, cause they will all bugg out and remain connected.

b1428ffbb3af0f7aa3d2533e29e6f9371581f43f

**Comment by zThundy** [comment]
i had this issue with the vrp 1.0 and i fixed this just creating a simple function that gets only the steamid and uses it to find the user_id of the player like it does by default. I noticed that this bug happens on player that have errors with their steam, so if vrp uses another identifier, like discord or license, vrp crashes and the player does not load properly

**Comment by colormeblind23** [comment]
Would love to know if this issue was ever resolved. How it was resolved and where to make the necessary changes to resolve it

**Comment by Sharky521** [comment]
Currently not an issue on fresh vrp2 server.
