### ISSUE TITLE
Audio Error

### ISSUE THREAD

**Issue by bradxy** [vRP-framework/vRP#478]
People are reporting this new Audio Error in vRP2... 

The same error can be found in the log, sometimes people report the error displaying 2 or more times on the top of there screen upon connecting to vrp

![audio error vrp2](https://user-images.githubusercontent.com/36649225/51068635-d8bd1b00-15d5-11e9-99ab-968cd9d1db20.JPG)

The voip is working well and connects fine for each user

**Comment by bradxy** [comment]
Please create a new topic, I don't think this is at all related to my error, do you have your VoIP server running and is it connecting to the VoIP server in F8 upon loading vrp2...

**Comment by AceDax** [comment]
umm that I honestly don't know, I set up my vRP2 server according to the instructions, I don't remember seeing anything about an VoIP server. I will go through and look again just to make sure it is all set up correctly. If I still experience this issue after doing that I will put in a separate ticket

**Comment by bradxy** [comment]
When you set up the voip server it should show connected in F8 once spawned

![capture](https://user-images.githubusercontent.com/36649225/51430069-69918900-1bca-11e9-9022-eb0c43d401b0.JPG)

**Comment by AceDax** [comment]
ok yeah looks like it is not set up for my server (sadface) anyways maybe I am blind or looking in the wrong place but I don't any instructions on how to set it up

**Comment by Sharky521** [comment]
Old issue. It seems to work fine in latest version.
