### ISSUE TITLE
Restart module

### ISSUE THREAD

**Issue by yuricampolongo** [vRP-framework/vRP#516]
I'm changing my server to user VRP 2 and i'm trying to use the old command:

restar vrp_xxxx (restart module) but i'm getting an error ' module already registered'.

There is a way to restart module in runtime?

**Comment by ImagicTheCat** [comment]
None yet, complicated to do.

**Comment by AleDema** [comment]
Please develop a workaround cause vrp2 right now is very annoying to work with

**Comment by ImagicTheCat** [comment]
Discord, 14/06/2020:
>  I wish we could just reload all FiveM resources without restarting the server and having FiveM triggering events as if the server was just starting and respawning everyone with a single command. But that would be a FiveM feature.

That may be a solution instead of expecting every resources to be restarted properly without a more complete resource manager.

**Comment by ChristianGabs** [comment]
We need a solution for this, restarting the server for any changes it's is a nightmare !

**Comment by Disquse** [comment]
I'm not sure how vRP2 works, but we was able to implement restarting feature in vRP1. TLDR the logic was about having a separate resource which would:
1) Register admin-only command that will first stop `vrp` then `vrp_mysql` (afaik this is not a thing anymore, yeah, this code is very old). Then it will start `vrp`.
2) Implement vRP logic to "reconnect" players. Basically you can easily modify main "playerConnecting" event to do this (except yeah, you don't need to use deferral). You can iterate over all players on server or even ask clients to "reconnect" themself.
I'm not sure how this might be implemented in vRP2 or even latest vRP1 versions, but this is not a hard task and you don't need any FiveM features, you already have everything you need to implement that.

**Comment by mickeygeecom** [comment]
We've added a "fakeLoad player" function.
On resource restart it just iterates all online players, similar to the playerConnect event. Just without deferrals.

**Comment by mickeygeecom** [comment]
We've added a "fakeLoad player" function.
On resource restart it just iterates all online players, similar to the playerConnect event. Just without deferrals.

**Comment by ImagicTheCat** [comment]
Discord
> As I have written some time ago, modules depend on each others and they can affect each others, thus you have to make all the API calls reversible and then expect resource authors to make sure they load/unload correctly. This is unlikely with FiveM. 
Otherwise you get some kind of undefined behavior when hot reloading the resources, which will stack up overtime. 
If the bottleneck is connecting to the server, it would be better to have FiveM implement a "full hot reload" of the server resources.

**Comment by SuelTheDev** [comment]
I managed to implement a solution, I don't know if it's the best but it works, at least for the scenario I was facing.
