### ISSUE TITLE
console print error   fps drop

### ISSUE THREAD

**Issue by ghost** [vRP-framework/vRP#572]
INFO: User [9] ModernRedNek authenticated - [3] [9] ModernRedNek@137.74.155.173:
52250:52250
[GHMattiMySQL ERROR] Parameter '@identifier' must be defined. To use this as a v
ariable, set 'Allow User Variables=true' in the connection string.
[GHMattiMySQL ERROR] Parameter '@identifier' must be defined. To use this as a v
ariable, set 'Allow User Variables=true' in the connection string.
[GHMattiMySQL ERROR] Parameter '@identifier' must be defined. To use this as a v
ariable, set 'Allow User Variables=true' in the connection string.
[GHMattiMySQL ERROR] Parameter '@num' must be defined. To use this as a variable
, set 'Allow User Variables=true' in the connection string.

can help me  fix this error ?

**Comment by Rusnacull** [comment]
Did you fix it ? y have it too

**Comment by IRAN-HIGH** [comment]
you are using vMenu ?

**Comment by Rusnacull** [comment]
No y am not  my discord account is Rusnacull#8660  Lets tolk Sent from Mail for Windows 10 From: IRAN-HIGH-RPSent: Friday, March 20, 2020 10:03 PMTo: ImagicTheCat/vRPCc: Rusnacull Costy Rus; CommentSubject: Re: [ImagicTheCat/vRP] console print error fps drop (#572) you are using vMenu ?—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Rusnacull** [comment]
y did fix it but now y have a problem with 
![ds](https://user-images.githubusercontent.com/43711421/77217950-0e8d5600-6b2f-11ea-8a5f-92c7780463ca.png)

**Comment by Rusnacull** [comment]
y fix the first one 
now y get this if a person connects mean the server is tarting
and then reconnects again

![sda](https://user-images.githubusercontent.com/43711421/77217984-5a3fff80-6b2f-11ea-8407-1190f6066359.png)

**Comment by zThundy** [comment]
the problem is inside a quary on the db. just check your quaries, expetially the ones that uses the players identifier

**Comment by Sharky521** [comment]
Old topic. 

If this issue is still encountered, update the database drivers and information to oxmysql
