### ISSUE TITLE
Disable VRP2 VOIP?

### ISSUE THREAD

**Issue by Kh4zy** [vRP-framework/vRP#593]
Hi, Im trying to disable the new implemented voip service by editing the audio.lua in vrp/config/ and set: cfg.vrp_voip = false

The issue is that I now get errors from the AudioEngine.js line 530: 
this.voip_ws.addEventListener("close", function(){
      console.log("vRP: VoIP disconnected");
    })

If i then comment that console log out, i get a message that the voip localhost url is blacklisted and blocked. Any way to come around that?

![20200223123731_1](https://user-images.githubusercontent.com/18709365/75111379-548ef100-5639-11ea-8bbc-83c1ac9df9c1.jpg)

Thanks in advance

**Comment by IRAN-HIGH** [comment]
hi . go to this address \resources\vrp\gui    and open this file AudioEngine.js   between line 508-533 remove all codes  this work 100% . sry mu english not enoth good

**Comment by Disquse** [comment]
This is because FiveM is not allowing to connect from CEF to localhost Websockets. This issue will be solved when you will move your server on a host.
