### ISSUE TITLE
Stuck on awaiting scripts

### ISSUE THREAD

**Issue by NylanderrDK** [vRP-framework/vRP#615]
Hi!

I just installed vRP on my localhost, and I don't experience any issues - either in the server console or F8.
When I'm joining I'm stuck on **awaiting scripts**.
I don't know what I can do to fix this.

**Comment by Thatman24** [comment]
Hi have you fixed this? I have the same problem

**Comment by jKorneto** [comment]
Is this resolved? Thank you

**Comment by FatalFrog** [comment]
Hey, I'm having the same issue, and I have no idea how to fix it, please, if anyone has even the slightest clue how to fix it, it would be appreciated if they posted it here.

**Comment by Sharky521** [comment]
For those still having this issue, make sure you are running the latest versions of FXServer and ensure that your database is configured correctly.
