### ISSUE TITLE
Having trouble to setting up the server 

### ISSUE THREAD

**Issue by LarrySheen** [vRP-framework/vRP#627]
Sorry to interrupt, I'm having some trouble to setup the server, I'm new to this framework and downloaded the 'master' tree which is 'vRP 2' -> I put the vRP floder under resource file directly. and here's few step I've taken so far...

I've added the [vrp_ghmattimysql](https://github.com/ImagicTheCat/vRP-db-drivers/tree/master/vrp_ghmattimysql)
and old version of [GHMattiMySQL](https://github.com/GHMatti/FiveM-MySQL/releases/tag/0.6.1)
to clear all the errors in the begging,
but theres still some errors sapming in console:
[vRP] DB driver “ghmattimysql" not initialized yet (39 prepares cached, 7 queries cached)

is there anything I missed ? is this framework still under going?
(hosting under localhost)
I'm planing hosting a strict-rp server with this framework, any suggestion&answers is appreciated !

**Comment by ELF0001** [comment]
make sure all database and Vrp file is in the mail ressource folder and not in a []

**Comment by LarrySheen** [comment]
> make sure all database and Vrp file is in the main ressource folder and not in a []

yes, that's what I did exactly.

**Comment by salvamr** [comment]
Same issue here 🤔

**Comment by LarrySheen** [comment]
> Same issue here but I'm using the newer version of GHMattiMySQL 🤔

Maybe you should use the old version if there's some "can't find resource file GHMattiMySQL" errors showed up, if you had the same error like I do, we need to wait then...

**Comment by sneakyazshiite** [comment]
@LarrySheen Did you happen to find a solution? I had a server I was tinkering with before the new fxmanifest with no issues. I tried creating a server now and did everything except the suggested "scheduler.lua" change. That doesn't seem to work with the latest fxserver builds.

**Comment by 1B0Y** [comment]
@sneakyazshiite Grab GHMattiMySQL's JS version, and then grab the js version of the db module. It'll fix it. Spent two days trying to figure it out.

**Comment by sneakyazshiite** [comment]
> 
> 
> @sneakyazshiite Grab GHMattiMySQL's JS version, and then grab the js version of the db module. It'll fix it. Spent two days trying to figure it out.

Tried that, showing "database server connection established" now. Unfortunately still populating the "driver not initialized" message.

![firefox_ljCPMaFMBP](https://user-images.githubusercontent.com/32582098/91381007-56a65800-e7f4-11ea-84f5-2694b380d60e.jpg)

**Comment by 1B0Y** [comment]
@sneakyazshiite I don't suppose you managed to figure out how to get passed "Awaiting Scripts" on connect? That's the only thing that's letting me down now and I honestly haven't got a clue what it could be 🤔

**Comment by sneakyazshiite** [comment]
> 
> 
> @sneakyazshiite I don't suppose you managed to figure out how to get passed "Awaiting Scripts" on connect? That's the only thing that's letting me down now and I honestly haven't got a clue what it could be 🤔

The only thing I can suggest is removing any extra resources and only launching with vrp stuff. From my limited experience the "awaiting scripts" derives from a script failing somewhere. If you've customized anything then you will want to trace those steps back to see what could have broke. I modified vRP a few months back and have not run into that issue fortunately.

**Comment by ImagicTheCat** [comment]
@sneakyazshiite You were supposed to change that line: https://github.com/ImagicTheCat/vRP/blob/master/vrp/cfg/base.lua#L6

**Comment by 1B0Y** [comment]
@sneakyazshiite I don't suppose you could add me on Discord could you? 1B0Y#9712

Tried stripping quite literally everything but to no avail, just wondering how you have your server.cfg setted up.
Thanks!

**Comment by 1B0Y** [comment]
Nevermind, fixed it - turns out I didn't have FiveM resource running like a potato 🤦‍♂️
