### ISSUE TITLE
Client fails to load code

### ISSUE THREAD

**Issue by itsaric** [vRP-framework/vRP#655]
https://github.com/ImagicTheCat/vRP/blob/0d5a18daa041ef4c95c8e808b6534102bd46c25f/vrp/lib/utils.lua#L27-L38

We have found that this seems to fail on the `if f then` check on the client-side only. We also can't seem to find a reason as to why it fails on that check.

**Comment by ImagicTheCat** [comment]
No error ?

**Comment by itsaric** [comment]
Errors weren't consistent. Some came from the same file at different points in the file, and there were no errors in that file. I suspect it has to do with `local code = LoadResourceFile(rsc, path..".lua")` not loading the code correctly? I know that's a cfx rpc but not sure if you have some insight on it?

**Comment by itsaric** [comment]
There are no actual syntactic errors in the file, as it loads the file fine most of the time.

**Comment by ImagicTheCat** [comment]
I don't think I can do much about it, but a good practice is to give the maximum amount of information you can about any issue you open (in this case, to show the actual errors).
