### ISSUE TITLE
Players Constantly timeout.

### ISSUE THREAD

**Issue by Bradman101** [vRP-framework/vRP#657]
Hi there, recently we have been having massive VRP server issues that have seen players constantly timing out for no reason. I was wondering if there is a reason or if there is something i can do to fix it??

![image](https://user-images.githubusercontent.com/71003251/158954285-a544bbc3-781f-48cf-bc86-a5fecfa68724.png)

**Comment by Sharky521** [comment]
It seems like your issues are related to the connection of your server host and not the vrp framework itself.
